services:

  db:
    image: postgres:16
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - mombapos_network


  web:
    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped

    depends_on:
      - db

    environment:
      RAILS_ENV: production

      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}

      POSTGRES_HOST: db
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}

    ports:
      - "127.0.0.1:3000:3000"

    networks:
      - mombapos_network


volumes:
  postgres_data:


networks:
  mombapos_network:
    driver: bridge